[aether]
localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python3

[forge]
devops-forge ansible_host=192.168.1.202 ansible_user=alikhan ansible_python_interpreter=/usr/bin/python3

[peer]
devops-peer ansible_host=192.168.1.201 ansible_user=alikhan ansible_python_interpreter=/usr/bin/python3
